# Build Multitarget Application & Deploy it to Cloud Foundry
name: Deploy to Demo Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
  
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run deploy
      
     
    # Do not generate package-lock.json
    # See https://blogs.sap.com/2020/07/07/escaping-eintegrity-hell/


     
  
   
        
  deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Deploy to Demo Server
         uses: goelanivrat/sapui5_conn@a3
         with:
           cf_host: ${{ secrets.CF_HOST }}
           cf_username: ${{ secrets.CF_USERNAME }}
           cf_password: ${{ secrets.CF_PASSWORD }}
           
